### ISSUE TITLE
Completing the 10th activation cause crash

### ISSUE THREAD

**Issue by Grokzen** [mmoench/krastorio2-extended-endgame#1]
Hi. I played through this mod after cmopleteing the normal krastorio2 gameplay. When i added the last sci packs for the 10th activation i got the following crash

![image](https://user-images.githubusercontent.com/892309/81117719-dba8f100-8f27-11ea-8ab4-a5695e0af18d.png)

I used the following set of mods if that is relevant

![image](https://user-images.githubusercontent.com/892309/81117753-ef545780-8f27-11ea-8cf9-73efe7f19830.png)

Game version 0.18.22 build 51330 Windows.

**Comment by mmoench** [comment]
Thank you for this report, I will look into the issue.

**Comment by Grokzen** [comment]
@mmoench I think i might found out what the issue is. When i played the normal krastorio2 gameplay i did build and activted their version of the intergalactic beacon structure. Then i addedyour extended version and it did not remove the old building but i could build a new beacon that was based on the extended mod. So when i had the old up i got the crash i posted above. When i removed the old building and put in the past sci packs the game completed correctly.

**Comment by mmoench** [comment]
Ah, I see, that makes sense: The original mod will not allow you to build a second transceiver. My mod will replace the building with krastorio's original building for the last activation, which fails in your case.
I'll publish a new version with a check to avoid this issue: You will be able to build multiple transceivers (maybe you want backups in case one gets destroyed?), but only one will get activated in the final stage.

**Comment by mmoench** [comment]
Should be fixed now with the new version 0.1.5, thanks again for the report.

**Comment by Grokzen** [comment]
Yeah it kinda makes sense to keep the original transceiver as when it is first activated it will provide 10GW of power and that is kinda the reason why i kept it around for the free energy
